PrivateSend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("storage.urls")),
    path("user/", include("user.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import SingupView
from .forms import AuthenticatedForm
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    path("register/", SingupView.as_view(), name='register'),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", form_class=AuthenticatedForm), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

user/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_field):
        if not email:
            raise ValueError("Harus Menggunakan Email")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_field)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_field):
        extra_field.setdefault("is_staff", False)
        extra_field.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_field)


    def create_superuser(self, email, password=None, **extra_field):
        extra_field.setdefault("is_staff", True)
        extra_field.setdefault("is_superuser", True)
        if extra_field.get("is_staff") is not True:
            raise ValueError(
            "superuser must have is_staff=True"
        )
        if extra_field.get("is_superuser") is not True:
            raise ValueError(
            "superuser must have is_superuser=True"
        )
        return self._create_user(email, password, **extra_field)
        

class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()
    
    def __str__(self):
        return f"{self.email}"


class AuditEntry(models.Model):
    action = models.CharField(max_length=64)
    ip = models.GenericIPAddressField(null=True)
    username = models.CharField(max_length=256, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '{0} - {1} - {2}'.format(self.action, self.username, self.ip)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.action, self.username, self.ip)


@receiver(user_logged_in)
def user_logged_in_callback(sender, request, user, **kwargs):  
    ip = request.META.get('REMOTE_ADDR')
    AuditEntry.objects.create(action='user_logged_in', ip=ip, username=user.email)


@receiver(user_logged_out)
def user_logged_out_callback(sender, request, user, **kwargs):  
    ip = request.META.get('REMOTE_ADDR')
    AuditEntry.objects.create(action='user_logged_out', ip=ip, username=user.email)


@receiver(user_login_failed)
def user_login_failed_callback(sender, credentials, **kwargs):
    AuditEntry.objects.create(action='user_login_failed', username=credentials.get('email', None))

user/forms.py
from django.contrib.auth.forms import (
 UserCreationForm as DjangoUserCreationForm
)
from django.core.mail import send_mail
from django import forms
from django.contrib.auth import authenticate
import logging
from django.contrib.auth.forms import UsernameField
from .models import User
logger = logging.getLogger(__name__)


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": UsernameField}
        def send_mail(self):
            logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
            )
            message = "Welcome{}".format(self.cleaned_data["email"])
            send_mail(
                "Welcome to Cloudimage",
                message,
                "site@climage.domain",
                [self.cleaned_data["email"]],
                fail_silently=True,
            )


class AuthenticatedForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email, password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                "invalid password and email"
            )
            logger.info(
                "Authenticated Success for email=%s", email
            )
        return self.cleaned_data 

    def get_user(self):
        return self.user

user/views.py
from django.shortcuts import render, get_object_or_404
import logging
from django.contrib.auth import login, authenticate

from django.contrib import messages
from django.views.generic.edit import FormView
from .forms import UserCreationForm
from taggit.models import Tag
from django.contrib.auth.mixins import LoginRequiredMixin




logger = logging.getLogger(__name__)

class SingupView(FormView):
    template_name = "register.html"
    form_class = UserCreationForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info(
            "New Singup for email=%s", email
        )
        user = authenticate(email=email, password=raw_password)
        login(self.request, user)
        form.send_mail()
        messages.info(
            self.request, "You Singup success"
        )
        return response

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-10 bg-gray-300">
    {% include 'include/header.html' %}
    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/main.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}

</body>
</html>

templates/include/header.html
{% load static %}

<header class="relative flex-none flex flex-row items-center justify-between w-full px-6 md:px-8 h-16 md:h-24 z-20 bg-transparent">
    <a href="/" class="flex flex-row items-center mt-4">
        <svg id="color" enable-background="new 0 0 24 24" height="100" viewBox="0 0 24 24" width="100" xmlns="http://www.w3.org/2000/svg"><path d="m18.671 4.93c-1.308-2.401-3.879-3.93-6.671-3.93-3.545 0-6.62 2.465-7.397 5.829-2.583.271-4.603 2.442-4.603 5.071 0 2.576 1.973 5.1 5.447 5.1-.289-.442-.447-.959-.447-1.5 0-1.403.768-1.906 2.556-3.694.79-.791 1.967-1.023 3-.595.705.292 1.233.856 1.5 1.54h4.194c1.517 0 2.75 1.233 2.75 2.75 0 .536-.16 1.033-.427 1.457 3.05-.348 5.427-2.917 5.427-6.028 0-3.067-2.307-5.623-5.329-6z" fill="#2196f3"/><path d="m12 1c-3.545 0-6.62 2.465-7.397 5.829-2.583.271-4.603 2.442-4.603 5.071 0 2.576 1.973 5.1 5.447 5.1-.289-.442-.447-.959-.447-1.5 0-1.403.768-1.906 2.556-3.694.527-.528 1.227-.807 1.941-.807.356 0 .715.069 1.059.212.659.273 1.164.784 1.444 1.407z" fill="#1d83d4"/><path d="m16.25 14.75h-6v-1c0-.665-.809-1.002-1.28-.53l-1.75 1.75c-.293.293-.293.768 0 1.061l1.75 1.75c.469.469 1.28.141 1.28-.53v-1h6c.414 0 .75-.336.75-.75 0-.415-.336-.751-.75-.751z" fill="#607d8b"/><path d="m17 15.5h-10c0 .192.073.384.22.53l1.75 1.75c.152.152.34.22.525.22.385 0 .756-.297.756-.751v-1h6c.413.001.749-.335.749-.749z" fill="#546d79"/><path d="m16.78 19.97-1.75-1.75c-.475-.474-1.28-.132-1.28.53v1h-6c-.414 0-.75.336-.75.75s.336.75.75.75h6v1c0 .669.811 1 1.28.53l1.75-1.75c.293-.293.293-.767 0-1.06z" fill="#607d8b"/><path d="m17 20.5h-10c0 .414.336.75.75.75h6v1c0 .453.371.75.757.75.184 0 .372-.068.524-.22l1.75-1.75c.146-.146.219-.338.219-.53z" fill="#546d79"/></svg>
        <h2 class="ml-4"><p class="text-3xl font-semibold">Storage Cloud</p></h2>
    </a>
    {% if user.is_authenticated %}
        <h1>Hai</h1>
    {% else %}
    <button class="bg-transparent hover:bg-blue-500  text-blue-700 font-semibold hover:text-white py-4 px-8 border border-blue-500 hover:border-transparent rounded transform transition duration-300 ease-in-out hover:-translate-y-1 hover:scale-100">
        <a href="{% url 'user:login' %}"><h2 class="text-lg">Masuk</h2></a>
    </button>
    {% endif %}
</header>

user/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}
{% load static %}
{% block content %}
<main class="main">
    <div class="flex items-center justify-center bg-white z-40 inset-x-0 top-0">
        <div class="h-full w-full max-h-screen absolute top-0 flex items-center justify-center">
            <div class="w-full">
                <div class="flex flex-col lg:flex-row justify-center px-8 md:px-24 w-full h-full">
                    <img src="{% static 'img/send.svg' %}" alt="" class="h-16 mt-1 mb-4">
                    <section class="flex flex-col flex-shrink-0 self-center lg:mx-6 lg:max-w-xs">
                        <h1 class="text-3xl font-bold text-center lg:text-left">
                            Buat Mengirim File Lebih Aman Masuk Atau Bikin Akun
                        </h1>
                        <ul class="leading-normal list-disc text-grey-80 my-2 mt-4 pl-4 md:self-center">
                            <li>Bagikan berkas kepada lebih banyak orang</li>
                            <li>Buat tautan aktif selama 7 hari</li>
                            <li>Kelola berkas yang dibagikan dari perangkat apa pun</li>
                        </ul>
                    </section>
                    <section class="flex flex-col flex-grow m-4 md:self-center md:w-128 lg:max-w-xs">
                        <form method="POST" action="">{% csrf_token %}
                            <input placeholder="Masukan Email Anda" type="email" id="id_email" name="email" value="{{ form.email.value|default:''}}" class="border rounded-lg w-full px-2 py-1 h-12 mb-3 text-lg text-grey-70 leading-loose">
                            <input  placeholder="Masukan password Anda" type="password" class="border rounded-lg w-full px-2 py-1 h-12 mb-3 text-lg text-grey-70 leading-loose" name="password" id="id_password">
                            <input title="Masuk" value="Masuk" type="submit" class="btn rounded-lg w-full flex flex-shrink-0 items-center justify-center hover:bg-blue-600">
                        </form>
                        <div class="flex mt-4 font-sans">
                            <a class="font-medium hover:text-blue-700" href="{% url 'user:register' %}">Register</a>
                            <a class="font-medium ml-56 hover:text-blue-700" href="/">Batal</a>
                        </div>
                        
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

user/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}
{% load static %}
{% block content %}
<main class="main">
    <div class="flex items-center justify-center bg-white z-40 inset-x-0 top-0">
        <div class="h-full w-full max-h-screen absolute top-0 flex items-center justify-center">
            <div class="w-full">
                <div class="flex flex-col lg:flex-row justify-center px-8 md:px-24 w-full h-full">
                    <img src="{% static 'img/send.svg' %}" alt="" class="h-16 mt-1 mb-4">
                    <section class="flex flex-col flex-shrink-0 self-center lg:mx-6 lg:max-w-xs">
                        <h1 class="text-3xl font-bold text-center lg:text-left">
                            Buat Mengirim File Lebih Aman Masuk Atau Bikin Akun
                        </h1>
                        <ul class="leading-normal list-disc text-grey-80 my-2 mt-4 pl-4 md:self-center">
                            <li>Bagikan berkas kepada lebih banyak orang</li>
                            <li>Buat tautan aktif selama 7 hari</li>
                            <li>Kelola berkas yang dibagikan dari perangkat apa pun</li>
                        </ul>
                    </section>
                    <section class="flex flex-col flex-grow m-4 md:self-center md:w-128 lg:max-w-xs">
                        <form method="POST" action="">{% csrf_token %}
                            <input placeholder="Masukan Email Anda" type="email" name="email" class="border rounded-lg w-full px-2 py-1 h-12 mb-3 text-lg text-grey-70 leading-loose" id="id_email" value="{{ form.email.value|default:''}}">
                            <input  placeholder="Masukan password Anda" type="password" class="border rounded-lg w-full px-2 py-1 h-12 mb-3 text-lg text-grey-70 leading-loose" name="password" id="id_password">
                            <input  placeholder="Cocokan password Anda" type="password2" class="border rounded-lg w-full px-2 py-1 h-12 mb-3 text-lg text-grey-70 leading-loose" name="password2" id="id_password">

                            <input title="Masuk" value="Masuk" type="submit" class="btn rounded-lg w-full flex flex-shrink-0 items-center justify-center hover:bg-blue-600">
                        </form>
                        <div class="flex mt-4 font-sans">
                            <a class="font-medium hover:text-blue-700" href="{% url 'user:login' %}">Login</a>
                            <a class="font-medium ml-56 hover:text-blue-700" href="/">Batal</a>
                        </div>
                        
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}